"use client";
import { ChangeEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { SignedIn } from "@clerk/nextjs";
import { AuthControls } from "./auth-controls";
import { useApiToken } from "./providers";
type Clause={id:string;sectionLabel:string;rawText:string;plainLanguageSummary:string;clauseType:string;riskLevel:string;riskExplanation?:string};
type Doc={id:string;title:string;clauses:Clause[]};
const api="/api";
export default function Home(){
 const router=useRouter();
 const getToken=useApiToken();
 const [doc,setDoc]=useState<Doc|null>(null),[busy,setBusy]=useState(false),[question,setQuestion]=useState(""),[answer,setAnswer]=useState(""),[other,setOther]=useState(""),[diff,setDiff]=useState(""),[error,setError]=useState("");
 async function request(url:string,options:RequestInit){const token=await getToken();const headers=new Headers(options.headers);if(token)headers.set("Authorization",`Bearer ${token}`);const r=await fetch(url,{...options,headers});const contentType=r.headers.get("content-type")??"";const data=contentType.includes("application/json")?await r.json():null;if(!r.ok)throw new Error(data?.error??"The server could not process this request. Please restart the app and try again.");if(!data)throw new Error("The server returned an invalid response. Please restart the app and try again.");return data}
 function openDocument(nextDoc:Doc){const history=JSON.parse(localStorage.getItem("murdock.documents")??"[]");localStorage.setItem("murdock.documents",JSON.stringify([{id:nextDoc.id,title:nextDoc.title,createdAt:new Date().toISOString()},...history.filter((item:{id:string})=>item.id!==nextDoc.id)].slice(0,25)));router.push(`/documents/${nextDoc.id}`)}
 async function sample(){try{setBusy(true);setError("");openDocument(await request(`${api}/documents/sample`,{method:"POST"}))}catch(e){setError(e instanceof Error?e.message:"Could not start sample.")}finally{setBusy(false)}}
 async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{setBusy(true);setError("");const form=new FormData();form.append("file",f);openDocument(await request(`${api}/documents`,{method:"POST",body:form}))}catch(e){setError(e instanceof Error?e.message:"Could not analyse file.")}finally{setBusy(false)}}
 async function ask(){if(!doc||!question)return;try{setError("");const data=await request(`${api}/documents/${doc.id}/ask`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});setAnswer(data.answer)}catch(e){setError(e instanceof Error?e.message:"Could not answer question.")}}
 async function compare(){if(!doc||!other)return;try{setError("");const data=await request(`${api}/compare`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leftDocumentId:doc.id,rightText:other})});setDiff(data.summary)}catch(e){setError(e instanceof Error?e.message:"Could not compare documents.")}}
 const flagged=useMemo(()=>doc?.clauses.filter(c=>c.riskLevel!=="LOW")??[],[doc]);
 if(!doc)return <main className="shell"><nav className="nav"><div className="brand">Mur<i>d</i>ock</div><div className="nav-right"><SignedIn><a className="btn ghost" href="/dashboard">Dashboard</a></SignedIn><span>Legal clarity, grounded in your document</span><AuthControls/></div></nav><section className="hero"><div className="eyebrow">AI-assisted document understanding</div><h1>Understand what your contract actually says.</h1><p>Upload a legal document to get clear section-by-section explanations, cited risk flags, comparisons, and questions to bring to a lawyer.</p><div className="notice">Murdock provides general information, not legal advice. Consult a qualified professional for advice about your situation.</div></section><section className="upload"><h3>{busy?"Parsing your document…":"Start with a document"}</h3><p>PDF, DOCX, or plain text. Murdock extracts a single structured clause graph that every feature reuses.</p>{busy&&<div className="loader" role="status"><span className="spinner"/>Reading clauses and mapping risks...</div>}{error&&<p className="form-error">{error}</p>}<div className="actions"><label className="btn">Choose a file<input className="file" type="file" accept=".txt,.pdf,.docx" onChange={upload} disabled={busy}/></label><button className="btn ghost" onClick={sample} disabled={busy}>{busy?"Please wait…":"Explore sample agreement"}</button></div></section><section className="how"><div><b>1. Extract once</b><p>Sections become source-linked clauses, not disconnected AI summaries.</p></div><div><b>2. Understand clearly</b><p>Read plain-language explanations directly beside original wording.</p></div><div><b>3. Act informed</b><p>Identify questions and topics worth discussing with a lawyer.</p></div></section><footer className="footer"><span>© 2026 Murdock · Information, not legal advice</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></div></footer></main>;
 return <main className="shell"><nav className="nav"><div className="brand">Mur<i>d</i>ock</div><div className="nav-right"><button className="btn ghost" onClick={()=>setDoc(null)}>New document</button><AuthControls/></div></nav>{error&&<p className="form-error">{error}</p>}<div className="notice">Informational, not legal advice. Every explanation and flag below links back to a clause in this document.</div><div className="workspace" style={{marginTop:18}}><section className="card"><div className="doc-head"><div><h2>{doc.title}</h2><span className="eyebrow">Structured clause view</span></div><span>{doc.clauses.length} clauses</span></div><div className="clauses">{doc.clauses.map(c=><article id={c.id} key={c.id} className={`clause ${c.riskLevel}`}><div className="meta">{c.sectionLabel} · {c.clauseType}</div><p>{c.rawText}</p><p className="summary">In plain language: {c.plainLanguageSummary}</p>{c.riskExplanation&&<p><b>Why this matters:</b> {c.riskExplanation}</p>}<span className="citation">Source: {c.sectionLabel}</span></article>)}</div></section><aside className="side"><section className="card"><h3>Risk label</h3><div className="score">{flagged.length}</div><p style={{fontSize:13,color:'#68786e'}}>clauses needing attention</p>{flagged.map(c=><div className="flag" key={c.id}><b>{c.riskLevel}</b> · <a href={`#${c.id}`}>{c.sectionLabel}</a></div>)}</section><section className="card"><h3>Ask Murdock</h3><div className="notice">Information only — not a substitute for legal advice.</div><div className="chat"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What does termination mean?"/><button className="btn" onClick={ask}>Ask</button></div>{answer&&<p className="answer">{answer}</p>}</section><section className="card"><h3>Compare another version</h3><textarea value={other} onChange={e=>setOther(e.target.value)} placeholder="Paste another agreement here…"/><button className="btn" style={{marginTop:8}} onClick={compare}>Compare clauses</button>{diff&&<div className="diff">{diff}</div>}</section><section className="card"><h3>Questions for a lawyer</h3>{flagged.map(c=><p style={{fontSize:13}} key={c.id}>• Could you explain the implications of {c.sectionLabel}? <span className="citation">[{c.sectionLabel}]</span></p>)}</section></aside></div></main>
}
